"""create_products_table

Revision ID: 3335c4391d22
Revises: 
Create Date: 2026-06-26 11:38:56.562926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3335c4391d22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
    "idx_products_cursor",
    "products",
    ["updated_at", "id"]
    )

    op.create_index(
    "idx_products_category",
    "products",
    ["category"]
    )

    op.create_index(
    "idx_products_price",
    "products",
    ["price"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_products_cursor", table_name="products")
    op.drop_index("idx_products_category", table_name="products")
    op.drop_index("idx_products_price", table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
