"""create_seed_metadata_table

Revision ID: fae029648e3c
Revises: 3335c4391d22
Create Date: 2026-07-02 23:29:56.164128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae029648e3c'
down_revision: Union[str, Sequence[str], None] = '3335c4391d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('generation_duration', sa.Float(), nullable=False),
    sa.Column('category_distribution', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_metadata')
    # ### end Alembic commands ###
